-
  name: commander command tester
  hosts: commanders
  tags: ['commander', 'command']
  vars:
    play_name: "{{ ansible_play_name }}"
    tool: "nslookup"
    parameter: "google.com"

  tasks:
    - name: '{{tool}} test...'
      command: "{{tool}} {{parameter}}"
      register: result
      ignore_errors: true

    - debug:
        msg: " âŒ  {{tool}} failed..."
      when: result is failed 

    - debug:
        msg: " ğŸ”  {{tool}} status changed..."
      when: result is changed

    - debug:
        msg: " â­ï¸  {{tool}} was skipped..."
      when: result is skipped

    - debug:
        msg: " âœ”ï¸  {{tool}} succeeded..."
      when: result is success

    - name: 'searching for package'
      shell: "dnf provides {{tool}} -q"
      register: result2
      ignore_errors: True
      when: result is failed
    
    - command: "echo {{ result2.stdout_lines[0] | regex_search('(.*)-[0-9]:?', '\\1') | first  }}"
      register: command_package
      when: result2 is success and result is failed 
    
    - ansible.builtin.debug:
        msg: " ğŸ“¦ found {{ command_package.stdout_lines[0] }}, attempting to install..."
      when: result2 is success and result is failed

    - command: "dnf -y install {{ command_package.stdout_lines[0] }}"
      when: result2 is success and result is failed

    - command: "{{tool}} {{parameter}}"
      register: result

    - name: '{{tool}} result'
      ansible.builtin.debug:
        msg: "{{result}}"

    - include_tasks: ../logs/write-commander-logs.yaml
      vars:
        event: "{{tool}} {{parameter}}"
        event_result: "{{result.stdout_lines[0]}}"